[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Rune580"
name = "LethalCompany_InputUtils"
description = "API/Library for creating Unity InputActions with in-game re-binding support. Provides an alternative UI that allows for supporting mods to have in-game re-bindable keybinds."
websiteUrl = "https://github.com/Rune580/LethalCompanyInputUtils"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icons/inpututils-static-icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LethalCompanyInputUtils/bin/Release/netstandard2.1/LethalCompanyInputUtils.dll"
target = "plugins/LethalCompanyInputUtils/"

[[build.copy]]
source = "../LethalCompanyInputUtils/bin/Release/netstandard2.1/LethalCompanyInputUtils.pdb"
target = "plugins/LethalCompanyInputUtils/"

[[build.copy]]
source = "../LethalCompanyInputUtils/bin/Release/netstandard2.1/AssetBundles"
target = "plugins/LethalCompanyInputUtils/AssetBundles"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE"
target = "/"

[publish]
communities = [ "lethal-company" ]

[publish.categories]
riskofrain2 = [ "mods", "libraries", "client-side" ]